/** Playground 路由表 — 与公开 export 对齐 */
export const playgroundRoutes = [
  { path: '/', label: '首页', group: '概览' },
  { path: '/list-recipe', label: 'ListPageRecipe', group: '配方' },
  { path: '/chat-recipe', label: 'ChatRecipe', group: '配方' },
  { path: '/app-dialog', label: 'AppDialog', group: '基础' },
  { path: '/app-icon', label: 'AppIcon', group: '基础' },
  { path: '/app-pagination', label: 'AppPagination', group: '数据展示' },
  { path: '/filter-tabs', label: 'FilterTabs', group: '基础' },
  { path: '/form-dialog', label: 'FormDialog', group: '弹框' },
  { path: '/confirm-dialog', label: 'ConfirmDialog', group: '弹框' },
  { path: '/page-shell', label: 'PageShell', group: 'Layout' },
  { path: '/page-header', label: 'PageHeader', group: 'Layout' },
  { path: '/breadcrumb-nav', label: 'BreadcrumbNav', group: 'Layout' },
  { path: '/content-panel', label: 'ContentPanel', group: 'Layout' },
  { path: '/filter-bar', label: 'FilterBar', group: 'Layout' },
  { path: '/card-table', label: 'CardTable', group: 'Layout' },
  { path: '/table-row-actions', label: 'TableRowActions', group: 'Layout' },
  { path: '/search-form', label: 'SearchForm', group: 'Layout' },
  { path: '/field-row', label: 'FieldRow', group: 'Property' },
  { path: '/hint-text', label: 'HintText', group: 'Property' },
  { path: '/section-toggle', label: 'SectionToggle', group: 'Property' },
  { path: '/truncated-tooltip', label: 'TruncatedTooltipText', group: 'Property' },
  { path: '/loading-dots', label: 'LoadingDots', group: 'Property' },
  { path: '/message-bubble', label: 'MessageBubble', group: 'Chat' },
  { path: '/message-list', label: 'MessageList', group: 'Chat' },
  { path: '/composer', label: 'Composer', group: 'Chat' },
  { path: '/run-status-bar', label: 'RunStatusBar', group: 'Chat' },
  { path: '/approval-card', label: 'ApprovalCard', group: 'Chat' },
  { path: '/message-parts', label: 'MessageParts', group: 'Chat' },
  { path: '/message-attachment-list', label: 'MessageAttachmentList', group: 'Chat' },
  { path: '/document-summary-list', label: 'DocumentSummaryList', group: 'Chat' },
  { path: '/attachment-preview-modal', label: 'AttachmentPreviewModal', group: 'Chat' },
  { path: '/session-sidebar', label: 'SessionSidebar', group: 'Chat' },
  { path: '/processing-drawer', label: 'ProcessingDrawer', group: 'Chat' },
  { path: '/conversation-header', label: 'ConversationHeader', group: 'Chat' },
  { path: '/assistant-picker', label: 'AssistantPicker', group: 'Chat' },
  { path: '/model-picker', label: 'ModelPicker', group: 'Chat' },
  { path: '/json-card', label: 'JsonCard', group: 'Preview' },
  { path: '/json-detail-dialog', label: 'JsonDetailDialog', group: 'Preview' },
  { path: '/schema-lite-preview', label: 'SchemaLitePreview', group: 'Preview' },
  { path: '/document-preview', label: 'DocumentPreview', group: 'Preview' },
  { path: '/pdf-preview-card', label: 'PdfPreviewCard', group: 'Preview' },
  { path: '/excel-preview-card', label: 'ExcelPreviewCard', group: 'Preview' },
  { path: '/empty-state', label: 'EmptyState', group: '反馈' },
  { path: '/error-boundary', label: 'ErrorBoundary', group: '反馈' },
  { path: '/status-tag', label: 'StatusTag', group: '反馈' },
  { path: '/skeleton', label: 'Skeleton', group: '反馈' },
  { path: '/card-grid-skeleton', label: 'CardGridSkeleton', group: '反馈' },
  { path: '/user-avatar', label: 'UserAvatar', group: '反馈' },
  { path: '/toast', label: 'Toast', group: '反馈' },
  { path: '/use-confirm', label: 'useConfirm', group: 'Composables' },
  { path: '/use-message', label: 'useMessage', group: 'Composables' },
  { path: '/use-debounce-fn', label: 'useDebounceFn', group: 'Composables' },
  { path: '/use-client-pagination', label: 'useClientPagination', group: 'Composables' },
  { path: '/use-data-loading', label: 'useDataLoading', group: 'Composables' },
  { path: '/use-chat-scroll', label: 'useChatScroll', group: 'Composables' },
  { path: '/use-toast', label: 'useToast', group: 'Composables' },
  // 历史路径别名（兼容旧链接）
  { path: '/dialog', label: 'AppDialog (alias)', group: '概览' },
  { path: '/confirm', label: 'useConfirm (alias)', group: '概览' },
  { path: '/message', label: 'useMessage (alias)', group: '概览' },
  { path: '/debounce', label: 'useDebounceFn (alias)', group: '概览' },
] as const

export const routeComponents: Record<string, () => Promise<{ default: unknown }>> = {
  '/': () => import('./views/Home.vue'),
  '/list-recipe': () => import('./views/ListPageRecipeDemo.vue'),
  '/chat-recipe': () => import('./views/ChatRecipeDemo.vue'),
  '/app-dialog': () => import('./views/AppDialogDemo.vue'),
  '/app-icon': () => import('./views/AppIconDemo.vue'),
  '/app-pagination': () => import('./views/AppPaginationDemo.vue'),
  '/filter-tabs': () => import('./views/FilterTabsDemo.vue'),
  '/form-dialog': () => import('./views/FormDialogDemo.vue'),
  '/confirm-dialog': () => import('./views/ConfirmDialogDemo.vue'),
  '/page-shell': () => import('./views/PageShellDemo.vue'),
  '/page-header': () => import('./views/PageHeaderDemo.vue'),
  '/breadcrumb-nav': () => import('./views/BreadcrumbNavDemo.vue'),
  '/content-panel': () => import('./views/ContentPanelDemo.vue'),
  '/filter-bar': () => import('./views/FilterBarDemo.vue'),
  '/card-table': () => import('./views/CardTableDemo.vue'),
  '/table-row-actions': () => import('./views/TableRowActionsDemo.vue'),
  '/search-form': () => import('./views/SearchFormDemo.vue'),
  '/field-row': () => import('./views/FieldRowDemo.vue'),
  '/hint-text': () => import('./views/HintTextDemo.vue'),
  '/section-toggle': () => import('./views/SectionToggleDemo.vue'),
  '/truncated-tooltip': () => import('./views/TruncatedTooltipTextDemo.vue'),
  '/loading-dots': () => import('./views/LoadingDotsDemo.vue'),
  '/message-bubble': () => import('./views/MessageBubbleDemo.vue'),
  '/message-list': () => import('./views/MessageListDemo.vue'),
  '/composer': () => import('./views/ComposerDemo.vue'),
  '/run-status-bar': () => import('./views/RunStatusBarDemo.vue'),
  '/approval-card': () => import('./views/ApprovalCardDemo.vue'),
  '/message-parts': () => import('./views/MessagePartsDemo.vue'),
  '/message-attachment-list': () => import('./views/MessageAttachmentListDemo.vue'),
  '/document-summary-list': () => import('./views/DocumentSummaryListDemo.vue'),
  '/attachment-preview-modal': () => import('./views/AttachmentPreviewModalDemo.vue'),
  '/session-sidebar': () => import('./views/SessionSidebarDemo.vue'),
  '/processing-drawer': () => import('./views/ProcessingDrawerDemo.vue'),
  '/conversation-header': () => import('./views/ConversationHeaderDemo.vue'),
  '/assistant-picker': () => import('./views/AssistantPickerDemo.vue'),
  '/model-picker': () => import('./views/ModelPickerDemo.vue'),
  '/json-card': () => import('./views/JsonCardDemo.vue'),
  '/json-detail-dialog': () => import('./views/JsonDetailDialogDemo.vue'),
  '/schema-lite-preview': () => import('./views/SchemaLitePreviewDemo.vue'),
  '/document-preview': () => import('./views/DocumentPreviewDemo.vue'),
  '/pdf-preview-card': () => import('./views/PdfPreviewCardDemo.vue'),
  '/excel-preview-card': () => import('./views/ExcelPreviewCardDemo.vue'),
  '/empty-state': () => import('./views/EmptyStateDemo.vue'),
  '/error-boundary': () => import('./views/ErrorBoundaryDemo.vue'),
  '/status-tag': () => import('./views/StatusTagDemo.vue'),
  '/skeleton': () => import('./views/SkeletonDemo.vue'),
  '/card-grid-skeleton': () => import('./views/CardGridSkeletonDemo.vue'),
  '/user-avatar': () => import('./views/UserAvatarDemo.vue'),
  '/toast': () => import('./views/ToastDemo.vue'),
  '/use-confirm': () => import('./views/ConfirmDemo.vue'),
  '/use-message': () => import('./views/MessageDemo.vue'),
  '/use-debounce-fn': () => import('./views/DebounceDemo.vue'),
  '/use-client-pagination': () => import('./views/PaginationDemo.vue'),
  '/use-data-loading': () => import('./views/UseDataLoadingDemo.vue'),
  '/use-chat-scroll': () => import('./views/UseChatScrollDemo.vue'),
  '/use-toast': () => import('./views/UseToastDemo.vue'),
  '/dialog': () => import('./views/AppDialogDemo.vue'),
  '/confirm': () => import('./views/ConfirmDemo.vue'),
  '/message': () => import('./views/MessageDemo.vue'),
  '/debounce': () => import('./views/DebounceDemo.vue'),
}
