/** Playground 路由表 — 仅真实组件 / Composables，对齐 Element Plus 文档结构 */
export const playgroundRoutes = [
  { path: '/', label: 'Overview', group: '指南' },
  { path: '/app-dialog', label: 'AppDialog', group: '基础' },
  { path: '/app-icon', label: 'AppIcon', group: '基础' },
  { path: '/filter-tabs', label: 'FilterTabs', group: '基础' },
  { path: '/app-pagination', label: 'AppPagination', group: '数据展示' },
  { path: '/form-dialog', label: 'FormDialog', group: '弹框' },
  { path: '/confirm-dialog', label: 'ConfirmDialog', group: '弹框' },
  { path: '/page-shell', label: 'PageShell', group: 'Layout' },
  { path: '/page-header', label: 'PageHeader', group: 'Layout' },
  { path: '/breadcrumb-nav', label: 'BreadcrumbNav', group: 'Layout' },
  { path: '/content-panel', label: 'ContentPanel', group: 'Layout' },
  { path: '/filter-bar', label: 'FilterBar', group: 'Layout' },
  { path: '/card-table', label: 'CardTable', group: 'Layout' },
  { path: '/table-row-actions', label: 'TableRowActions', group: 'Layout' },
  { path: '/search-form', label: 'SearchForm', group: 'Layout' },
  { path: '/field-row', label: 'FieldRow', group: 'Property' },
  { path: '/hint-text', label: 'HintText', group: 'Property' },
  { path: '/section-toggle', label: 'SectionToggle', group: 'Property' },
  { path: '/property-panel', label: 'PropertyPanel', group: 'Property' },
  { path: '/truncated-tooltip', label: 'TruncatedTooltipText', group: 'Property' },
  { path: '/loading-dots', label: 'LoadingDots', group: 'Property' },
  { path: '/message-bubble', label: 'MessageBubble', group: 'Chat' },
  { path: '/tip-banner', label: 'TipBanner', group: 'Chat' },
  { path: '/starter-prompt-grid', label: 'StarterPromptGrid', group: 'Chat' },
  { path: '/message-list', label: 'MessageList', group: 'Chat' },
  { path: '/composer', label: 'Composer', group: 'Chat' },
  { path: '/mention-input', label: 'MentionInput', group: 'Chat' },
  { path: '/thinking-block', label: 'ThinkingBlock', group: 'Chat' },
  { path: '/editable-artifact-card', label: 'EditableArtifactCard', group: 'Chat' },
  { path: '/message-action-bar', label: 'MessageActionBar', group: 'Chat' },
  { path: '/collapsible-step-card', label: 'CollapsibleStepCard', group: 'Chat' },
  { path: '/agent-transfer-card', label: 'AgentTransferCard', group: 'Chat' },
  { path: '/field-list-card', label: 'FieldListCard', group: 'Chat' },
  { path: '/flow-node-strip-card', label: 'FlowNodeStripCard', group: 'Chat' },
  { path: '/token-usage-card', label: 'TokenUsageCard', group: 'Chat' },
  { path: '/questionnaire-card', label: 'QuestionnaireCard', group: 'Chat' },
  { path: '/checklist-proposal-card', label: 'ChecklistProposalCard', group: 'Chat' },
  { path: '/requirement-analysis-card', label: 'RequirementAnalysisCard', group: 'Chat' },
  { path: '/document-detail-summary-card', label: 'DocumentDetailSummaryCard', group: 'Chat' },
  { path: '/error-recovery-card', label: 'ErrorRecoveryCard', group: 'Chat' },
  { path: '/variable-diff-card', label: 'VariableDiffCard', group: 'Chat' },
  { path: '/sub-workflow-status-card', label: 'SubWorkflowStatusCard', group: 'Chat' },
  { path: '/ppt-preview-card', label: 'PptPreviewCard', group: 'Chat' },
  { path: '/flow-preview-shell', label: 'FlowPreviewShell', group: 'Chat' },
  { path: '/bpmn-flow-preview-canvas', label: 'BpmnFlowPreviewCanvas', group: 'Chat' },
  { path: '/model-3d-preview-card', label: 'Model3dPreviewCard', group: 'Chat' },
  { path: '/image-generate-card', label: 'ImageGenerateCard', group: 'Chat' },
  { path: '/schema-form-preview', label: 'SchemaFormPreview', group: 'Chat' },
  { path: '/workflow-run-timeline', label: 'WorkflowRunTimeline', group: 'Chat' },
  { path: '/suggestion-card', label: 'SuggestionCard', group: 'Chat' },
  { path: '/conversation-search-bar', label: 'ConversationSearchBar', group: 'Chat' },
  { path: '/task-chain-bar', label: 'TaskChainBar', group: 'Chat' },
  { path: '/rag-context-panel', label: 'RagContextPanel', group: 'Chat' },
  { path: '/run-status-bar', label: 'RunStatusBar', group: 'Chat' },
  { path: '/approval-card', label: 'ApprovalCard', group: 'Chat' },
  { path: '/message-parts', label: 'MessageParts', group: 'Chat' },
  { path: '/message-attachment-list', label: 'MessageAttachmentList', group: 'Chat' },
  { path: '/document-summary-list', label: 'DocumentSummaryList', group: 'Chat' },
  { path: '/attachment-preview-modal', label: 'AttachmentPreviewModal', group: 'Chat' },
  { path: '/session-sidebar', label: 'SessionSidebar', group: 'Chat' },
  { path: '/processing-drawer', label: 'ProcessingDrawer', group: 'Chat' },
  { path: '/conversation-header', label: 'ConversationHeader', group: 'Chat' },
  { path: '/assistant-picker', label: 'AssistantPicker', group: 'Chat' },
  { path: '/model-picker', label: 'ModelPicker', group: 'Chat' },
  { path: '/json-card', label: 'JsonCard', group: 'Preview' },
  { path: '/json-detail-dialog', label: 'JsonDetailDialog', group: 'Preview' },
  { path: '/schema-lite-preview', label: 'SchemaLitePreview', group: 'Preview' },
  { path: '/document-preview', label: 'DocumentPreviewPanel', group: 'Preview' },
  { path: '/pdf-preview-card', label: 'PdfPreviewCard', group: 'Preview' },
  { path: '/excel-preview-card', label: 'ExcelPreviewCard', group: 'Preview' },
  { path: '/artifact-gallery', label: 'ArtifactGallery', group: 'Preview' },
  { path: '/execution-artifact-panel', label: 'ExecutionArtifactPanel', group: 'Preview' },
  { path: '/empty-state', label: 'EmptyState', group: '反馈' },
  { path: '/error-boundary', label: 'ErrorBoundary', group: '反馈' },
  { path: '/status-tag', label: 'StatusTag', group: '反馈' },
  { path: '/skeleton', label: 'Skeleton', group: '反馈' },
  { path: '/card-grid-skeleton', label: 'CardGridSkeleton', group: '反馈' },
  { path: '/user-avatar', label: 'UserAvatar', group: '反馈' },
  { path: '/app-user-panel', label: 'AppUserPanel', group: '反馈' },
  { path: '/slider-captcha', label: 'SliderCaptcha', group: '反馈' },
  { path: '/toast', label: 'Toast', group: '反馈' },
  { path: '/time-range-picker', label: 'TimeRangePicker', group: '监控' },
  { path: '/metric-chart', label: 'MetricChart', group: '监控' },
  { path: '/stat-card', label: 'StatCard', group: '监控' },
  { path: '/severity-badge', label: 'SeverityBadge', group: '监控' },
  { path: '/service-grid', label: 'ServiceGrid', group: '监控' },
  { path: '/status-timeline', label: 'StatusTimeline', group: '监控' },
  { path: '/log-stream', label: 'LogStream', group: '监控' },
  { path: '/threshold-slider', label: 'ThresholdSlider', group: '监控' },
  { path: '/use-confirm', label: 'useConfirm', group: 'Composables' },
  { path: '/use-message', label: 'useMessage', group: 'Composables' },
  { path: '/use-debounce-fn', label: 'useDebounceFn', group: 'Composables' },
  { path: '/use-client-pagination', label: 'useClientPagination', group: 'Composables' },
  { path: '/use-data-loading', label: 'useDataLoading', group: 'Composables' },
  { path: '/use-chat-scroll', label: 'useChatScroll', group: 'Composables' },
  { path: '/use-clipboard', label: 'useClipboard', group: 'Composables' },
  { path: '/use-toast', label: 'useToast', group: 'Composables' },
  { path: '/use-realtime', label: 'useRealtime', group: 'Composables' },
] as const

export const routeComponents: Record<string, () => Promise<{ default: unknown }>> = {
  '/': () => import('./views/Home.vue'),
  '/app-dialog': () => import('./views/AppDialogDemo.vue'),
  '/app-icon': () => import('./views/AppIconDemo.vue'),
  '/app-pagination': () => import('./views/AppPaginationDemo.vue'),
  '/filter-tabs': () => import('./views/FilterTabsDemo.vue'),
  '/form-dialog': () => import('./views/FormDialogDemo.vue'),
  '/confirm-dialog': () => import('./views/ConfirmDialogDemo.vue'),
  '/page-shell': () => import('./views/PageShellDemo.vue'),
  '/page-header': () => import('./views/PageHeaderDemo.vue'),
  '/breadcrumb-nav': () => import('./views/BreadcrumbNavDemo.vue'),
  '/content-panel': () => import('./views/ContentPanelDemo.vue'),
  '/filter-bar': () => import('./views/FilterBarDemo.vue'),
  '/card-table': () => import('./views/CardTableDemo.vue'),
  '/table-row-actions': () => import('./views/TableRowActionsDemo.vue'),
  '/search-form': () => import('./views/SearchFormDemo.vue'),
  '/field-row': () => import('./views/FieldRowDemo.vue'),
  '/hint-text': () => import('./views/HintTextDemo.vue'),
  '/section-toggle': () => import('./views/SectionToggleDemo.vue'),
  '/property-panel': () => import('./views/PropertyPanelDemo.vue'),
  '/truncated-tooltip': () => import('./views/TruncatedTooltipTextDemo.vue'),
  '/loading-dots': () => import('./views/LoadingDotsDemo.vue'),
  '/message-bubble': () => import('./views/MessageBubbleDemo.vue'),
  '/tip-banner': () => import('./views/TipBannerDemo.vue'),
  '/starter-prompt-grid': () => import('./views/StarterPromptGridDemo.vue'),
  '/message-list': () => import('./views/MessageListDemo.vue'),
  '/composer': () => import('./views/ComposerDemo.vue'),
  '/mention-input': () => import('./views/MentionInputDemo.vue'),
  '/thinking-block': () => import('./views/ThinkingBlockDemo.vue'),
  '/editable-artifact-card': () => import('./views/EditableArtifactCardDemo.vue'),
  '/message-action-bar': () => import('./views/MessageActionBarDemo.vue'),
  '/collapsible-step-card': () => import('./views/CollapsibleStepCardDemo.vue'),
  '/agent-transfer-card': () => import('./views/AgentTransferCardDemo.vue'),
  '/field-list-card': () => import('./views/FieldListCardDemo.vue'),
  '/flow-node-strip-card': () => import('./views/FlowNodeStripCardDemo.vue'),
  '/token-usage-card': () => import('./views/TokenUsageCardDemo.vue'),
  '/questionnaire-card': () => import('./views/QuestionnaireCardDemo.vue'),
  '/checklist-proposal-card': () => import('./views/ChecklistProposalCardDemo.vue'),
  '/requirement-analysis-card': () => import('./views/RequirementAnalysisCardDemo.vue'),
  '/document-detail-summary-card': () => import('./views/DocumentDetailSummaryCardDemo.vue'),
  '/error-recovery-card': () => import('./views/ErrorRecoveryCardDemo.vue'),
  '/variable-diff-card': () => import('./views/VariableDiffCardDemo.vue'),
  '/sub-workflow-status-card': () => import('./views/SubWorkflowStatusCardDemo.vue'),
  '/ppt-preview-card': () => import('./views/PptPreviewCardDemo.vue'),
  '/flow-preview-shell': () => import('./views/FlowPreviewShellDemo.vue'),
  '/bpmn-flow-preview-canvas': () => import('./views/BpmnFlowPreviewCanvasDemo.vue'),
  '/model-3d-preview-card': () => import('./views/Model3dPreviewCardDemo.vue'),
  '/image-generate-card': () => import('./views/ImageGenerateCardDemo.vue'),
  '/schema-form-preview': () => import('./views/SchemaFormPreviewDemo.vue'),
  '/workflow-run-timeline': () => import('./views/WorkflowRunTimelineDemo.vue'),
  '/suggestion-card': () => import('./views/SuggestionCardDemo.vue'),
  '/conversation-search-bar': () => import('./views/ConversationSearchBarDemo.vue'),
  '/task-chain-bar': () => import('./views/TaskChainBarDemo.vue'),
  '/rag-context-panel': () => import('./views/RagContextPanelDemo.vue'),
  '/run-status-bar': () => import('./views/RunStatusBarDemo.vue'),
  '/approval-card': () => import('./views/ApprovalCardDemo.vue'),
  '/message-parts': () => import('./views/MessagePartsDemo.vue'),
  '/message-attachment-list': () => import('./views/MessageAttachmentListDemo.vue'),
  '/document-summary-list': () => import('./views/DocumentSummaryListDemo.vue'),
  '/attachment-preview-modal': () => import('./views/AttachmentPreviewModalDemo.vue'),
  '/session-sidebar': () => import('./views/SessionSidebarDemo.vue'),
  '/processing-drawer': () => import('./views/ProcessingDrawerDemo.vue'),
  '/conversation-header': () => import('./views/ConversationHeaderDemo.vue'),
  '/assistant-picker': () => import('./views/AssistantPickerDemo.vue'),
  '/model-picker': () => import('./views/ModelPickerDemo.vue'),
  '/json-card': () => import('./views/JsonCardDemo.vue'),
  '/json-detail-dialog': () => import('./views/JsonDetailDialogDemo.vue'),
  '/schema-lite-preview': () => import('./views/SchemaLitePreviewDemo.vue'),
  '/document-preview': () => import('./views/DocumentPreviewDemo.vue'),
  '/pdf-preview-card': () => import('./views/PdfPreviewCardDemo.vue'),
  '/excel-preview-card': () => import('./views/ExcelPreviewCardDemo.vue'),
  '/artifact-gallery': () => import('./views/ArtifactGalleryDemo.vue'),
  '/execution-artifact-panel': () => import('./views/ExecutionArtifactPanelDemo.vue'),
  '/empty-state': () => import('./views/EmptyStateDemo.vue'),
  '/error-boundary': () => import('./views/ErrorBoundaryDemo.vue'),
  '/status-tag': () => import('./views/StatusTagDemo.vue'),
  '/skeleton': () => import('./views/SkeletonDemo.vue'),
  '/card-grid-skeleton': () => import('./views/CardGridSkeletonDemo.vue'),
  '/user-avatar': () => import('./views/UserAvatarDemo.vue'),
  '/app-user-panel': () => import('./views/AppUserPanelDemo.vue'),
  '/slider-captcha': () => import('./views/SliderCaptchaDemo.vue'),
  '/toast': () => import('./views/ToastDemo.vue'),
  '/time-range-picker': () => import('./views/TimeRangePickerDemo.vue'),
  '/metric-chart': () => import('./views/MetricChartDemo.vue'),
  '/stat-card': () => import('./views/StatCardDemo.vue'),
  '/severity-badge': () => import('./views/SeverityBadgeDemo.vue'),
  '/service-grid': () => import('./views/ServiceGridDemo.vue'),
  '/status-timeline': () => import('./views/StatusTimelineDemo.vue'),
  '/log-stream': () => import('./views/LogStreamDemo.vue'),
  '/threshold-slider': () => import('./views/ThresholdSliderDemo.vue'),
  '/use-confirm': () => import('./views/ConfirmDemo.vue'),
  '/use-message': () => import('./views/MessageDemo.vue'),
  '/use-debounce-fn': () => import('./views/DebounceDemo.vue'),
  '/use-client-pagination': () => import('./views/PaginationDemo.vue'),
  '/use-data-loading': () => import('./views/UseDataLoadingDemo.vue'),
  '/use-chat-scroll': () => import('./views/UseChatScrollDemo.vue'),
  '/use-clipboard': () => import('./views/UseClipboardDemo.vue'),
  '/use-toast': () => import('./views/UseToastDemo.vue'),
  '/use-realtime': () => import('./views/UseRealtimeDemo.vue'),
}
